CREATE TABLE `bible_version` (
  `id` int(3) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `abbreviation` text NOT NULL COMMENT 'Version Abbreviation',
  `language` text NOT NULL COMMENT 'Language of bible translation (used for language key tables)',
  `version` text CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL COMMENT 'Version Name',
  `info_url` text NOT NULL COMMENT 'Info URL',
  `published` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=latin1 AUTO_INCREMENT=29 ;

INSERT INTO `bible_version` VALUES (1, 'RV60', 'Español', 'Biblia Reina Valera 1960', 'https://en.wikipedia.org/wiki/Reina-Valera', 1);


CREATE TABLE `bible_rv60_books` (
  `id` int(11) UNSIGNED NOT NULL,
  `name` varchar(50) COLLATE latin1_spanish_ci NOT NULL,
  `abreviation` varchar(10) COLLATE latin1_spanish_ci NOT NULL,
  `testament` varchar(1) COLLATE latin1_spanish_ci NOT NULL,
  `genre` varchar(45) COLLATE latin1_spanish_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci COMMENT='Libros de la Biblia';


INSERT INTO `bible_rv60_books` (`id`, `name`, `abreviation`, `testament`, `genre`) VALUES
(1, 'Génesis', '', 'O', ''),
(2, 'Éxodo', '', 'O', ''),
(3, 'Levítico', '', 'O', ''),
(4, 'Números', '', 'O', ''),
(5, 'Deuteronomio', '', 'O', ''),
(6, 'Josué', '', 'O', ''),
(7, 'Jueces', '', 'O', ''),
(8, 'Rut', '', 'O', ''),
(9, '1 Samuel', '', 'O', ''),
(10, '2 Samuel', '', 'O', ''),
(11, '1 Reyes', '', 'O', ''),
(12, '2 Reyes', '', 'O', ''),
(13, '1 Crónicas', '', 'O', ''),
(14, '2 Crónicas', '', 'O', ''),
(15, 'Esdras', '', 'O', ''),
(16, 'Nehemías', '', 'O', ''),
(17, 'Ester', '', 'O', ''),
(18, 'Job', '', 'O', ''),
(19, 'Salmos', '', 'O', ''),
(20, 'Proverbios', '', 'O', ''),
(21, 'Eclesiastés', '', 'O', ''),
(22, 'Cantares', '', 'O', ''),
(23, 'Isaías', '', 'O', ''),
(24, 'Jeremías', '', 'O', ''),
(25, 'Lamentaciones', '', 'O', ''),
(26, 'Ezequiel', '', 'O', ''),
(27, 'Daniel', '', 'O', ''),
(28, 'Oseas', '', 'O', ''),
(29, 'Joel', '', 'O', ''),
(30, 'Amós', '', 'O', ''),
(31, 'Abdías', '', 'O', ''),
(32, 'Jonás', '', 'O', ''),
(33, 'Miqueas', '', 'O', ''),
(34, 'Nahúm', '', 'O', ''),
(35, 'Habacuc', '', 'O', ''),
(36, 'Sofonías', '', 'O', ''),
(37, 'Hageo', '', 'O', ''),
(38, 'Zacarías', '', 'O', ''),
(39, 'Malaquías', '', 'O', ''),
(40, 'Mateo', '', 'N', ''),
(41, 'Marcos', '', 'N', ''),
(42, 'Lucas', '', 'N', ''),
(43, 'Juan', '', 'N', ''),
(44, 'Hechos', '', 'N', ''),
(45, 'Romanos', '', 'N', ''),
(46, '1 Corintios', '', 'N', ''),
(47, '2 Corintios', '', 'N', ''),
(48, 'Gálatas', '', 'N', ''),
(49, 'Efesios', '', 'N', ''),
(50, 'Filipenses', '', 'N', ''),
(51, 'Colosenses', '', 'N', ''),
(52, '1 Tesalonicenses', '', 'N', ''),
(53, '2 Tesalonicenses', '', 'N', ''),
(54, '1 Timoteo', '', 'N', ''),
(55, '2 Timoteo', '', 'N', ''),
(56, 'Tito', '', 'N', ''),
(57, 'Filemón', '', 'N', ''),
(58, 'Hebreos', '', 'N', ''),
(59, 'Santiago', '', 'N', ''),
(60, '1 Pedro', '', 'N', ''),
(61, '2 Pedro', '', 'N', ''),
(62, '1 Juan', '', 'N', ''),
(63, '2 Juan', '', 'N', ''),
(64, '3 Juan', '', 'N', ''),
(65, 'Judas', '', 'N', ''),
(66, 'Apocalipsis', '', 'N', '');
